create table if not exists board_column
(
    id                bigint generated by default as identity
    primary key,
    created_by        varchar(255),
    creation_date     timestamp(6),
    is_deleted        boolean not null,
    last_modified_by  varchar(255),
    updated_date      timestamp(6),
    board_column_uuid varchar(36),
    color             varchar(255),
    is_visible        boolean,
    label             varchar(255)
    constraint uk_3d15rr5pri2gyomqgy84kh0gw
    unique,
    position          integer
    );

alter table board_column
    owner to postgres;

create table if not exists control_criteria
(
    id                    bigint generated by default as identity
    primary key,
    created_by            varchar(255),
    creation_date         timestamp(6),
    is_deleted            boolean not null,
    last_modified_by      varchar(255),
    updated_date          timestamp(6),
    control_criteria_uuid varchar(36),
    code                  varchar(255),
    name                  varchar(255)
    );

alter table control_criteria
    owner to postgres;

create table if not exists customer
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    customer_uuid    varchar(36),
    code             varchar(255),
    name             varchar(255)
    );

alter table customer
    owner to postgres;

create table if not exists document
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    document_uuid    varchar(36),
    code             varchar(255),
    data             bytea,
    name             varchar(255),
    type             varchar(255)
    );

alter table document
    owner to postgres;

create table if not exists equipment
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    equipment_uuid   varchar(36),
    code             varchar(255),
    name             varchar(255)
    );

alter table equipment
    owner to postgres;

create table if not exists equipment_route_types
(
    equipment_id bigint not null
    constraint fk8rwmllboyud0bvp0fvyya2v3h
    references equipment,
    route_type   varchar(255)
    );

alter table equipment_route_types
    owner to postgres;

create table if not exists inspection_at_source_production
(
    id                                  bigint generated by default as identity
    primary key,
    created_by                          varchar(255),
    creation_date                       timestamp(6),
    is_deleted                          boolean not null,
    last_modified_by                    varchar(255),
    updated_date                        timestamp(6),
    inpection_at_source_production_uuid varchar(36),
    amount                              numeric(38, 2),
    barcode_number                      varchar(255),
    description                         varchar(255),
    event_time                          timestamp(6),
    is_first                            boolean,
    is_match                            boolean,
    is_send                             boolean,
    operator_user_id                    bigint,
    production_id                       bigint,
    read_time                           timestamp(6)
    );

alter table inspection_at_source_production
    owner to postgres;

create table if not exists inspection_at_source_production_document
(
    id                                bigint generated by default as identity
    primary key,
    created_by                        varchar(255),
    creation_date                     timestamp(6),
    is_deleted                        boolean not null,
    last_modified_by                  varchar(255),
    updated_date                      timestamp(6),
    inpection_at_source_document_uuid varchar(36),
    data                              bytea,
    description                       varchar(255),
    document_upload_date              timestamp(6),
    name                              varchar(255),
    operator_user_id                  bigint,
    production_id                     bigint,
    type                              varchar(255)
    );

alter table inspection_at_source_production_document
    owner to postgres;

create table if not exists issue
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    issue_uuid       varchar(36),
    board_column_id  bigint,
    description      varchar(255),
    name             varchar(255),
    priority         varchar(255),
    tags             varchar(255),
    user_id          bigint
    );

alter table issue
    owner to postgres;

create table if not exists last_quality_control_production
(
    id                           bigint generated by default as identity
    primary key,
    created_by                   varchar(255),
    creation_date                timestamp(6),
    is_deleted                   boolean not null,
    last_modified_by             varchar(255),
    updated_date                 timestamp(6),
    last_quality_control_uuid    varchar(36),
    amount                       numeric(38, 2),
    barcode_number               varchar(255),
    description_of_current_user  varchar(255),
    description_of_previous_user varchar(255),
    end_time                     timestamp(6),
    event_time                   timestamp(6),
    is_accepted                  boolean,
    last_quality_control_status  varchar(255),
    manufactured_by_user_id      bigint,
    manufacturing_time           timestamp(6),
    operator_user_id             bigint,
    production_id                bigint,
    quality_status               varchar(255),
    rework_description           varchar(255),
    start_time                   timestamp(6),
    test_status                  varchar(255)
    );

alter table last_quality_control_production
    owner to postgres;

create table if not exists line
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    line_uuid        varchar(36),
    code             varchar(255),
    name             varchar(255)
    );

alter table line
    owner to postgres;

create table if not exists machine
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    machine_uuid     varchar(36),
    code             varchar(255),
    name             varchar(255)
    );

alter table machine
    owner to postgres;

create table if not exists manufacture_production
(
    id                          bigint generated by default as identity
    primary key,
    created_by                  varchar(255),
    creation_date               timestamp(6),
    is_deleted                  boolean not null,
    last_modified_by            varchar(255),
    updated_date                timestamp(6),
    manufacture_production_uuid varchar(36),
    amount                      numeric(38, 2),
    description                 varchar(255),
    end_time                    timestamp(6),
    operator_user_id            bigint,
    production_id               bigint,
    start_time                  timestamp(6)
    );

alter table manufacture_production
    owner to postgres;

create table if not exists manufacture_with_barcode_production
(
    id                                       bigint generated by default as identity
    primary key,
    created_by                               varchar(255),
    creation_date                            timestamp(6),
    is_deleted                               boolean not null,
    last_modified_by                         varchar(255),
    updated_date                             timestamp(6),
    manufacture_with_barcode_production_uuid varchar(36),
    amount                                   numeric(38, 2),
    barcode_number                           varchar(255),
    description                              varchar(255),
    event_time                               timestamp(6),
    is_first                                 boolean,
    is_match                                 boolean,
    is_send                                  boolean,
    operator_user_id                         bigint,
    production_id                            bigint,
    read_time                                timestamp(6)
    );

alter table manufacture_with_barcode_production
    owner to postgres;

create table if not exists planning_production
(
    id                       bigint generated by default as identity
    primary key,
    created_by               varchar(255),
    creation_date            timestamp(6),
    is_deleted               boolean not null,
    last_modified_by         varchar(255),
    updated_date             timestamp(6),
    planning_production_uuid varchar(36),
    production_id            bigint
    );

alter table planning_production
    owner to postgres;

create table if not exists product
(
    id                       bigint generated by default as identity
    primary key,
    created_by               varchar(255),
    creation_date            timestamp(6),
    is_deleted               boolean not null,
    last_modified_by         varchar(255),
    updated_date             timestamp(6),
    product_uuid             varchar(36),
    barcode_number           varchar(255),
    category                 varchar(255),
    definition               varchar(255),
    is_approve               boolean,
    is_defined               boolean,
    is_verified              boolean,
    location                 varchar(255),
    manufacture_part_number1 varchar(255),
    manufacture_part_number2 varchar(255),
    manufacture_part_number3 varchar(255),
    quantity_per_unit        numeric(38, 2),
    roketsan_part_number     varchar(255),
    sequence                 bigint,
    test_description         varchar(255),
    total_quantity           numeric(38, 2),
    unit                     varchar(255),
    work_order_id            bigint
    );

alter table product
    owner to postgres;

create table if not exists production
(
    id                  bigint generated by default as identity
    primary key,
    created_by          varchar(255),
    creation_date       timestamp(6),
    is_deleted          boolean not null,
    last_modified_by    varchar(255),
    updated_date        timestamp(6),
    production_uuid     varchar(36),
    end_time            timestamp(6),
    is_startable        boolean,
    route_id            bigint,
    start_time          timestamp(6),
    status              varchar(255),
    work_order_id       bigint,
    work_order_route_id bigint
    );

alter table production
    owner to postgres;

create table if not exists production_production_references_document_list
(
    production_id                       bigint not null
    constraint fkk6lfohfogy0w31yo45kpdx0oq
    references production,
    production_references_document_list bigint
);

alter table production_production_references_document_list
    owner to postgres;

create table if not exists production_control_criteria
(
    id                               bigint generated by default as identity
    primary key,
    created_by                       varchar(255),
    creation_date                    timestamp(6),
    is_deleted                       boolean not null,
    last_modified_by                 varchar(255),
    updated_date                     timestamp(6),
    production_control_criteria_uuid varchar(36),
    control_criteria_id              bigint,
    is_checked                       boolean,
    production_id                    bigint
    );

alter table production_control_criteria
    owner to postgres;

create table if not exists production_delivery_production
(
    id                        bigint generated by default as identity
    primary key,
    created_by                varchar(255),
    creation_date             timestamp(6),
    is_deleted                boolean not null,
    last_modified_by          varchar(255),
    updated_date              timestamp(6),
    production_receiving_uuid varchar(36),
    amount                    numeric(38, 2),
    barcode_number            varchar(255),
    description               varchar(255),
    event_time                timestamp(6),
    is_match                  boolean,
    manufactured_user_id      bigint,
    operator_user_id          bigint,
    production_id             bigint,
    read_time                 timestamp(6)
    );

alter table production_delivery_production
    owner to postgres;

create table if not exists production_document
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    document_uuid    varchar(36),
    code             varchar(255),
    data             bytea,
    name             varchar(255),
    production_id    bigint,
    type             varchar(255),
    version_number   integer
    );

alter table production_document
    owner to postgres;

create table if not exists production_equipment
(
    id                        bigint generated by default as identity
    primary key,
    created_by                varchar(255),
    creation_date             timestamp(6),
    is_deleted                boolean not null,
    last_modified_by          varchar(255),
    updated_date              timestamp(6),
    production_equipment_uuid varchar(36),
    equipment_id              bigint,
    production_id             bigint
    );

alter table production_equipment
    owner to postgres;

create table if not exists production_log
(
    id                  bigint generated by default as identity
    primary key,
    created_by          varchar(255),
    creation_date       timestamp(6),
    is_deleted          boolean not null,
    last_modified_by    varchar(255),
    updated_date        timestamp(6),
    production_log_uuid varchar(36),
    description         varchar(255),
    event_time          timestamp(6),
    event_type_enum     varchar(255),
    production_id       bigint,
    rest_cause_id       bigint,
    user_id             bigint,
    work_order_id       bigint
    );

alter table production_log
    owner to postgres;

create table if not exists quality_production
(
    id                           bigint generated by default as identity
    primary key,
    created_by                   varchar(255),
    creation_date                timestamp(6),
    is_deleted                   boolean not null,
    last_modified_by             varchar(255),
    updated_date                 timestamp(6),
    quality_production_uuid      varchar(36),
    amount                       numeric(38, 2),
    barcode_number               varchar(255),
    description_of_current_user  varchar(255),
    description_of_previous_user varchar(255),
    end_time                     timestamp(6),
    event_time                   timestamp(6),
    is_accepted                  boolean,
    is_contain_barcode           boolean,
    manufactured_by_user_id      bigint,
    manufacturing_time           timestamp(6),
    operator_user_id             bigint,
    outage_amount                numeric(38, 2),
    production_id                bigint,
    quality_status               varchar(255),
    rejected_amount              numeric(38, 2),
    rework_description           varchar(255),
    start_time                   timestamp(6)
    );

alter table quality_production
    owner to postgres;

create table if not exists rest_cause
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    rest_cause_uuid  varchar(36),
    code             varchar(255)
    constraint uk_8gfoml3wy69e6irhnc6p3wbm5
    unique,
    is_mandatory     boolean,
    name             varchar(255)
    );

alter table rest_cause
    owner to postgres;

create table if not exists role
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    uuid             varchar(36),
    description      varchar(255),
    is_staff         boolean,
    name             varchar(255)
    constraint uk_8sewwnpamngi6b1dwaa88askk
    unique
    );

alter table role
    owner to postgres;

create table if not exists route
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    route_uuid       varchar(36),
    code             varchar(255),
    description      varchar(255),
    name             varchar(255),
    route_type_enum  varchar(255)
    );

alter table route
    owner to postgres;

create table if not exists route_roles
(
    routes_id bigint not null
    constraint fk1acu1poq0wwmro5htbxqilvae
    references route,
    roles_id  bigint not null
    constraint fkolu7fe4miol65hbviv2eik2wa
    references role,
    primary key (routes_id, roles_id)
    );

alter table route_roles
    owner to postgres;

create table if not exists route_template
(
    id                  bigint generated by default as identity
    primary key,
    created_by          varchar(255),
    creation_date       timestamp(6),
    is_deleted          boolean not null,
    last_modified_by    varchar(255),
    updated_date        timestamp(6),
    route_template_uuid varchar(36),
    name                varchar(255)
    );

alter table route_template
    owner to postgres;

create table if not exists route_template_route
(
    id                        bigint generated by default as identity
    primary key,
    created_by                varchar(255),
    creation_date             timestamp(6),
    is_deleted                boolean not null,
    last_modified_by          varchar(255),
    updated_date              timestamp(6),
    route_template_route_uuid varchar(36),
    order_number              integer,
    related_route_id          bigint,
    route_id                  bigint,
    route_template_id         bigint
    );

alter table route_template_route
    owner to postgres;

create table if not exists route_template_route_control_criteria_list
(
    route_template_route_id bigint not null
    constraint fkt1d788pvowkht7hcheijp6n94
    references route_template_route,
    control_criteria_list   bigint
);

alter table route_template_route_control_criteria_list
    owner to postgres;

create table if not exists route_template_route_references_document_list
(
    route_template_route_id  bigint not null
    constraint fkfgtvo2qcbc660n0xhtc1btwg8
    references route_template_route,
    references_document_list bigint
);

alter table route_template_route_references_document_list
    owner to postgres;

create table if not exists shift
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    shift_uuid       varchar(36),
    end_time         time,
    name             varchar(255),
    start_time       time
    );

alter table shift
    owner to postgres;

create table if not exists test_production
(
    id                           bigint generated by default as identity
    primary key,
    created_by                   varchar(255),
    creation_date                timestamp(6),
    is_deleted                   boolean not null,
    last_modified_by             varchar(255),
    updated_date                 timestamp(6),
    test_production_uuid         varchar(36),
    amount                       numeric(38, 2),
    barcode_number               varchar(255),
    description_of_current_user  varchar(255),
    description_of_previous_user varchar(255),
    end_time                     timestamp(6),
    event_time                   timestamp(6),
    is_accepted                  boolean,
    manufactured_by_user_id      bigint,
    manufacturing_time           timestamp(6),
    operator_user_id             bigint,
    production_id                bigint,
    quality_status               varchar(255),
    rework_description           varchar(255),
    start_time                   timestamp(6),
    test_status                  varchar(255)
    );

alter table test_production
    owner to postgres;

create table if not exists upload_delivery_document_production
(
    id                                       bigint generated by default as identity
    primary key,
    created_by                               varchar(255),
    creation_date                            timestamp(6),
    is_deleted                               boolean not null,
    last_modified_by                         varchar(255),
    updated_date                             timestamp(6),
    upload_delivery_document_production_uuid varchar(36),
    data                                     bytea,
    description                              varchar(255),
    document_upload_date                     timestamp(6),
    name                                     varchar(255),
    operator_user_id                         bigint,
    production_id                            bigint,
    type                                     varchar(255)
    );

alter table upload_delivery_document_production
    owner to postgres;

create table if not exists users
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean      not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    uuid             varchar(36),
    email            varchar(255) not null,
    first_name       varchar(255),
    is_enable        boolean,
    last_name        varchar(255),
    password         varchar(255) not null,
    photo_link       varchar(255),
    username         varchar(255)
    );

alter table users
    owner to postgres;

create table if not exists users_roles
(
    users_id bigint not null
    constraint fkml90kef4w2jy7oxyqv742tsfc
    references users,
    roles_id bigint not null
    constraint fk15d410tj6juko0sq9k4km60xq
    references role,
    primary key (users_id, roles_id)
    );

alter table users_roles
    owner to postgres;

create table if not exists ware_house
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    ware_house_uuid  varchar(36),
    code             varchar(255),
    description      varchar(255),
    name             varchar(255)
    );

alter table ware_house
    owner to postgres;

create table if not exists warehouse_receiving_production
(
    id                           bigint generated by default as identity
    primary key,
    created_by                   varchar(255),
    creation_date                timestamp(6),
    is_deleted                   boolean not null,
    last_modified_by             varchar(255),
    updated_date                 timestamp(6),
    warehouse_receiving_uuid     varchar(36),
    amount                       numeric(38, 2),
    barcode_number               varchar(255),
    description_of_current_user  varchar(255),
    description_of_previous_user varchar(255),
    event_time                   timestamp(6),
    is_match                     boolean,
    last_quality_control_status  smallint,
    manufactured_user_id         bigint,
    operator_user_id             bigint,
    production_id                bigint,
    read_time                    timestamp(6)
    );

alter table warehouse_receiving_production
    owner to postgres;

create table if not exists work_centre
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    work_centre_uuid varchar(36),
    code             varchar(255),
    description      varchar(255),
    name             varchar(255)
    );

alter table work_centre
    owner to postgres;

create table if not exists work_order
(
    id                         bigint generated by default as identity
    primary key,
    created_by                 varchar(255),
    creation_date              timestamp(6),
    is_deleted                 boolean not null,
    last_modified_by           varchar(255),
    updated_date               timestamp(6),
    work_order_uuid            varchar(36),
    amount                     numeric(38, 2),
    customer_id                bigint,
    customer_work_order_date   timestamp(6),
    customer_work_order_number varchar(255),
    nato_stock_code            varchar(255),
    order_number               varchar(255),
    part_number                varchar(255),
    planning_end_date_time     timestamp(6),
    planning_start_date_time   timestamp(6),
    product_revision_number    varchar(255),
    project_name               varchar(255),
    serial_number_end          varchar(255),
    serial_number_start        varchar(255),
    status                     varchar(255),
    work_order_number          varchar(255)
    );

alter table work_order
    owner to postgres;

create table if not exists work_order_document
(
    id               bigint generated by default as identity
    primary key,
    created_by       varchar(255),
    creation_date    timestamp(6),
    is_deleted       boolean not null,
    last_modified_by varchar(255),
    updated_date     timestamp(6),
    document_uuid    varchar(36),
    code             varchar(255),
    data             bytea,
    document_date    date,
    name             varchar(255),
    type             varchar(255),
    version_number   integer,
    work_order_id    bigint
    );

alter table work_order_document
    owner to postgres;

create table if not exists work_order_route
(
    id                      bigint generated by default as identity
    primary key,
    created_by              varchar(255),
    creation_date           timestamp(6),
    is_deleted              boolean not null,
    last_modified_by        varchar(255),
    updated_date            timestamp(6),
    work_order_route_uuid   varchar(36),
    leader_staff_id         bigint,
    routeid                 bigint,
    route_template_id       bigint,
    route_template_route_id bigint,
    work_order_id           bigint
    );

alter table work_order_route
    owner to postgres;

create table if not exists work_order_route_staff_list
(
    work_order_route_id bigint not null
    constraint fkrnw9em8q60gsulwtp380c6p5
    references work_order_route,
    staff_list          bigint
);

alter table work_order_route_staff_list
    owner to postgres;

