package com.comitfy.kidefy.app.model;

public enum RouteTypeEnum {

    PLANNING,
    CUSTOM,
    BOM_KIT_DEFINITION,
    BOM_KIT_VALIDATION,
    QUALITY,
    PRODUCTION,
    PRODUCTION_WITH_BARCODE,
    TEST,
    WAREHOUSE_DELIVERY,
    DELIVERY,
    LAST_QUALITY_CONTROL,
    INSPECTION_AT_SOURCE,
    UPLOADING_DELIVERY_DOCUMENTS,
    SETUP_VERIFICATION,
    ASSEMBLY_ARRANGEMENT,
    MANUAL_ASSEMBLY_ARRANGEMENT,
    BOXED_DELIVERY;


}
